# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e10733d32f22f07d60fbb2126581f5c8552f232ad789c827564a320306c7964ed8afd6f06568cde6273e129e9f9b95b4cdde1992d4c50907694208d3d2440187

test:
  secret_key_base: 9f85de928d3c4370c7c30ca452e5f1c1bfd49f9c8debb103c16199c5249f3f8f26efda4a597d55fb164412a334ec05674120a456e572e0779c97c87c2ef30066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
